# Time scheduler api version
@baseURL = http://localhost:8000/api/v1/tasks
### POST the task list
POST {{baseURL}}
Content-Type: application/json

{
    "task": "Football",
    "hr": 20,
    "type": "entry"
}
### GET the task list
GET {{baseURL}}
### Update the task list
PATCH {{baseURL}}
Content-Type: application/json


{
    "_id": "67da5891f02ed00c81c93588",
    "hr": 25,
    "type": "entry"
}
### Delete the task list
DELETE {{baseURL}}/67da5502f02ed00c81c93584