# Time scheduler api version
@baseURL = http://localhost:8000/api/v1/tasks
### POST the task list
POST {{baseURL}}
Content-Type: application/json

{
    "task": "Volleyball",
    "hr": 10,
    "type": "entry"
}
### GET the task list
GET {{baseURL}}
### Update the task list
PATCH {{baseURL}}
Content-Type: application/json


{
    "_id": "67dba8b24a521e7d6abe7069",
    "hr": 15,
    "type": "entry"
}
### Delete the task list
DELETE {{baseURL}}
Content-Type: application/json

[
    "66b8531bc60351964ff91c24",
    "66b85418c60351964ff91c26"
]